# 训练Xception模型，并保存权重

1 使用 Xception

2 冻结训练分类器

3 finetune训练整个网络

### 1 import libs

In [1]:
from keras.models import * 
from keras.layers import *
from keras.applications import *
from keras.preprocessing.image import *
from keras.utils.training_utils import multi_gpu_model
import tensorflow as tf

Using TensorFlow backend.


In [2]:
from keras.backend.tensorflow_backend import set_session
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.95
#config.gpu_options = tf.GPUOptions(allow_growth=True)
set_session(tf.Session(config=config))

### 2 build pretrained model

In [2]:
with tf.device('/cpu:0'):
    input_tensor = Input((299, 299, 3))
    x = Lambda(xception.preprocess_input)(input_tensor)

    base_model = Xception(input_tensor=x, weights='imagenet', include_top=False)
    base_model.summary()
    m_out = base_model.output
    p_out = GlobalAveragePooling2D()(m_out)
    p_out = Dropout(0.5)(p_out)
    predictions = Dense(2, activation='softmax')(p_out)

    for layer in base_model.layers:
        layer.trainable = False

    model = Model(inputs=base_model.input, outputs=predictions)
    model.summary()

parallel_model = multi_gpu_model(model, gpus=2)
parallel_model.compile(optimizer='Adadelta', 
                       loss='categorical_crossentropy', 
                       metrics=['accuracy'])
parallel_model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 299, 299, 3)  0                                            
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 299, 299, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 149, 149, 32) 864         lambda_1[0][0]                   
__________________________________________________________________________________________________
block1_conv1_bn (BatchNormaliza (None, 149, 149, 32) 128         block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_con

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 299, 299, 3)  0                                            
__________________________________________________________________________________________________
lambda_2 (Lambda)               (None, 299, 299, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
lambda_3 (Lambda)               (None, 299, 299, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
model_1 (Model)                 (None, 2)            20865578    lambda_2[0][0]                   
                                                                 lambda_3[0][0]                   
__________

### 3 build param

In [10]:
batch_size = 128
epochs = 1

total_imgs_num = 1722553 + 95694
train_imgs_num = 1722553
valid_imgs_num = 95694

img_size = (299, 299)

### 4 build data & train

In [11]:
img_gen_t = ImageDataGenerator()
train_generator = img_gen_t.flow_from_directory("/usr/super-speed-data/train-data-xception-pre/20181023/train-ready/", 
                                                img_size, shuffle=True, batch_size=batch_size)

img_gen_v = ImageDataGenerator()
valid_generator = img_gen_v.flow_from_directory("/usr/super-speed-data/train-data-xception-pre/20181023/valid-ready/",
                                                img_size, shuffle=True, batch_size=batch_size)


parallel_model.fit_generator(generator=train_generator, 
                             steps_per_epoch=train_imgs_num//batch_size, 
                             epochs=epochs, 
                             verbose=1,
                             validation_data=valid_generator, 
                             validation_steps=valid_imgs_num//batch_size)

model.save_weights("Xception_first_train.h5")

Found 1722553 images belonging to 2 classes.
Found 95694 images belonging to 2 classes.
Epoch 1/1
13457/13457 [==============================] - 5313s 395ms/step - loss: 0.3667 - acc: 0.8383 - val_loss: 0.4674 - val_acc: 0.7803


### 5 Finetune

In [2]:
with tf.device('/cpu:0'):
    input_tensor = Input((299, 299, 3))
    x = Lambda(xception.preprocess_input)(input_tensor)

    base_model = Xception(input_tensor=x, weights=None, include_top=False)
    m_out = base_model.output
    p_out = GlobalAveragePooling2D()(m_out)
    p_out = Dropout(0.5)(p_out)
    predictions = Dense(2, activation='softmax')(p_out)
    model = Model(inputs=base_model.input, outputs=predictions)
    model.load_weights('Xception_first_train.h5')

parallel_model = multi_gpu_model(model, gpus=2)
parallel_model.compile(optimizer='Adadelta', 
                       loss='categorical_crossentropy', 
                       metrics=['accuracy'])
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 299, 299, 3)  0                                            
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 299, 299, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 149, 149, 32) 864         lambda_1[0][0]                   
__________________________________________________________________________________________________
block1_conv1_bn (BatchNormaliza (None, 149, 149, 32) 128         block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_con

In [4]:
batch_size = 48
epochs = 5

total_imgs_num = 1722553 + 95694
train_imgs_num = 1722553
valid_imgs_num = 95694

img_size = (299, 299)

img_gen_t = ImageDataGenerator(rotation_range= 90,                            
                               width_shift_range= 0.1,
                               height_shift_range= 0.1,
                               zoom_range= 0.1,
                               brightness_range=[0.9, 1.1],
#                               zca_whitening= True,
                               horizontal_flip= True,
                               vertical_flip= True)

train_generator = img_gen_t.flow_from_directory("/usr/super-speed-data/train-data-xception-pre/20181023/train-ready/", 
                                                img_size, shuffle=True, batch_size=batch_size)

img_gen_v = ImageDataGenerator()
valid_generator = img_gen_v.flow_from_directory("/usr/super-speed-data/train-data-xception-pre/20181023/valid-ready/", 
                                                img_size, shuffle=True, batch_size=batch_size)


parallel_model.fit_generator(generator=train_generator, steps_per_epoch=train_imgs_num//batch_size, epochs=epochs, verbose=1,
                   validation_data=valid_generator, validation_steps=valid_imgs_num//batch_size)

gen = ImageDataGenerator()

model.save_weights("Xception_finetune_10.h5")

Found 1722553 images belonging to 2 classes.
Found 95694 images belonging to 2 classes.
Epoch 1/5
35886/35886 [==============================] - 27417s 764ms/step - loss: 0.0062 - acc: 0.9977 - val_loss: 0.0764 - val_acc: 0.9845
Epoch 2/5
35886/35886 [==============================] - 27349s 762ms/step - loss: 0.0057 - acc: 0.9979 - val_loss: 0.0463 - val_acc: 0.9892
Epoch 3/5
35886/35886 [==============================] - 26979s 752ms/step - loss: 0.0055 - acc: 0.9980 - val_loss: 0.0443 - val_acc: 0.9900
Epoch 4/5
35886/35886 [==============================] - 26958s 751ms/step - loss: 0.0056 - acc: 0.9980 - val_loss: 0.0508 - val_acc: 0.9931
Epoch 5/5
35886/35886 [==============================] - 27039s 753ms/step - loss: 0.0052 - acc: 0.9981 - val_loss: 0.0097 - val_acc: 0.9973


In [6]:
batch_size = 128
img_size = (299, 299)

gen = ImageDataGenerator()
test_generator = gen.flow_from_directory("/usr/super-speed-data/train-data-xception-pre/20181023/test-ready/", 
                                         img_size, 
                                         shuffle=False,
                                         batch_size=batch_size)
test_img_nums = test_generator.samples
test = parallel_model.predict_generator(test_generator, (test_img_nums//batch_size) + 1, verbose=1)
test = test[:test_img_nums]
label = test_generator.classes

Found 95694 images belonging to 2 classes.
748/748 [==============================] - 313s 418ms/step


In [7]:
print(test.shape)
print(label.shape)

(95694, 2)
(95694,)


In [8]:
print(len(test))
print(len(label))

print(test[0])
print(np.argmax(test[0]))

true_nums = 0
total_nums = len(label)
for i in range(len(label)):
    if(label[i] == np.argmax(test[i])):
        true_nums = true_nums + 1

print(true_nums)
print(total_nums)
print(true_nums / total_nums)

95694
95694
[0.5805131  0.41948688]
0
95391
95694
0.9968336572825882


### 5 load weights & predict

In [43]:
input_tensor = Input((299, 299, 3))
x = Lambda(xception.preprocess_input)(input_tensor)

base_model = Xception(input_tensor=x, weights=None, include_top=False)
m_out = base_model.output
p_out = GlobalAveragePooling2D()(m_out)
p_out = Dropout(1.0)(p_out)
fc_out = Dense(1024, activation='relu')(p_out)
fc_out = Dropout(1.0)(fc_out)
predictions = Dense(3, activation='softmax')(fc_out)
model = Model(inputs=base_model.input, outputs=predictions)
model.load_weights('Xception.h5')

In [44]:
img_gen_s = ImageDataGenerator()
submit_generator = img_gen_t.flow_from_directory("../dataset/test", img_size, shuffle=False, batch_size=2)

predictions = []
for i, batch_data in enumerate(submit_generator):
    if (i > 1):
        break
    batch_img_data = np.array(batch_data[0])
    predictions.extend(model.predict_on_batch(batch_img_data))
    print(i)
    
print(predictions)

Found 14 images belonging to 3 classes.
0
1
[array([ 0.30176267,  0.35524741,  0.34298989], dtype=float32), array([ 0.28475785,  0.34978592,  0.36545616], dtype=float32), array([ 0.3018229 ,  0.35525236,  0.34292471], dtype=float32), array([ 0.29986629,  0.35433695,  0.34579682], dtype=float32)]


In [45]:
print(np.array(predictions))

[[ 0.30176267  0.35524741  0.34298989]
 [ 0.28475785  0.34978592  0.36545616]
 [ 0.3018229   0.35525236  0.34292471]
 [ 0.29986629  0.35433695  0.34579682]]


### 6 write predictions 2 CSV